nodes:
  - name: 'node-1'
    msp_id: 'MyPeer1MSP'
    address: 'http://substra-backend.node-1.com'
    user: 'substra'
    password: 'p@$swr0d44'
  - name: 'node-2'
    msp_id: 'MyPeer2MSP'
    address: 'http://substra-backend.node-2.com'
    user: 'substra'
    password: 'p@$swr0d44'
